### ISSUE TITLE
problems with config_encoder_filters

### ISSUE THREAD

**Issue by kostyrev** [jtyr/ansible-environment#1]
installing this role with `ansible-galaxy install` does download config_encoder_filters causing ansible-playbook to fail with

```
ERROR! the role 'config_encoder_filters' was not found
The error appears to have been in '/home/kostyrev/control/roles/jtyr.environment/meta/main.yml': line 18, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

dependencies:
  - config_encoder_filters
    ^ here
```

**Comment by jtyr** [comment]
Sorry but I don't support Ansible Galaxy dependency resolution. I recommend to install the dependency separately and then use Ansible Galaxy to download the role.

**Comment by jtyr** [comment]
More details [here](https://github.com/jtyr/ansible-config_encoder_filters#usage).
